### ISSUE TITLE
Don't work for me (manjaro, both ways of installation)

### ISSUE THREAD

**Issue by grenudi** [ArchI3Chris/LightTable-Square-Fix#2]
can give any information to solve the issue.

**Comment by ArchI3Chris** [comment]
I've just seen your message. I'm not sure, if you have found a solution yet.

Basically, the solution did work and a number of people have confirmed that. But I've stated before, that LightTable seems to be behind on development and might have been discontinued. So, it's just a matter of time, until it doesn't work anymore. As far as I can see, even the most recent of changed are 6 months behind. The change log actually seems to be 5 years behind. The copyright on the website is the same age (2014).

The offered fix is for a particular problem (squares instead of letters in dialogs like open and save). It's not an ultimate solution for everything.

So, unfortunately, I have to agree. At this point, even on Arch I don't even get it running anymore and get a segement fault.

But honestly, to me it's not that important. I suggest you try and use one of many alternative options. Like for example, Sublime Text. Although, you might either want to buy it or it's quite annoying. The next best thing, according to my experience, is Visual Studio Code.
